export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_START: "categorie/FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCESS: "categorie/FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAILURE: "categorie/FETCH_CATEGORIES_FAILURE",
};